//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EMail { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> PictureId { get; set; }
        public bool IsTeacher { get; set; }
        public bool IsParent { get; set; }
        public bool Disabled { get; set; }
    }
}
